modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "${version}"
displayName = "NeoMTR Pro Max"
authors = "Jonathan Ho & Zbx1425 & LX86"
description = "A Minecraft mod that adds automated train systems into the game."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mtr.mixins.json"

[[mixins]]
config = "mtrsteamloco.mixins.json"

[[mixins]]
config = "mtr-common.mixins.json"

[[mixins]]
config = "jsblock-common.mixins.json"

[[mixins]]
config = "mtrtm-common.mixins.json"

[[mixins]]
config = "mtrtdm-common.mixins.json"

[[mixins]]
config = "msd-common.mixins.json"