modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "${version}"
displayName = "NeoMTR"
authors = "Jonathan Ho & Zbx1425"
description = "A Minecraft mod that adds automated train systems into the game."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mtr.mixins.json"
